### ISSUE TITLE
[Install] 2. Prepare Drivers

### ISSUE THREAD

**Issue by BernardoMadeira** [oscimp/oscimpDigital#1]
Hello everyone,

I am really interested in trying your platform for resonator characterization, but unfortunately I am having some trouble with the installation on the RedPitaya (14 bit version).

After running **sudo make install_nfsdir** (https://github.com/oscimp/oscimpDigital/wiki/2Prepare#drivers)
I made sure to follow every instruction, including adding Path and sourcing the variables.

`bernardo@bernardo-ThinkPad-X230:~/oscimpDigital/linux_driver$ sudo make install_nfsdir
make -C add_const_core install; make -C axi_to_dac_core install; make -C data_dma_direct_core install; make -C data_to_ram_core install; make -C edfb_core install; make -C fft_core install; make -C fir_core install; make -C fpgagen_core install; make -C nco_counter_core install; make -C pidv3_axi_core install; make -C redpitaya_converters_12_core install; make -C switch_core install;
make[1]: Entering directory '/home/bernardo/oscimpDigital/linux_driver/add_const_core'
Makefile:2: /Makefile.inc: No such file or directory
make[1]: *** No rule to make target '/Makefile.inc'.  Stop.
make[1]: Leaving directory '/home/bernardo/oscimpDigital/linux_driver/add_const_core'
make[1]: Entering directory '/home/bernardo/oscimpDigital/linux_driver/axi_to_dac_core'
Makefile:2: /Makefile.inc: No such file or directory
(...) for all instances
make[1]: Leaving directory '/home/bernardo/oscimpDigital/linux_driver/redpitaya_converters_12_core'
make[1]: Entering directory '/home/bernardo/oscimpDigital/linux_driver/switch_core'
Makefile:2: /Makefile.inc: No such file or directory
make[1]: *** No rule to make target '/Makefile.inc'.  Stop.
make[1]: Leaving directory '/home/bernardo/oscimpDigital/linux_driver/switch_core'
Makefile:7: recipe for target 'install_nfsdir' failed
make: *** [install_nfsdir] Error 2`

Running only **make install_nfsdir** yields:

`bernardo@bernardo-ThinkPad-X230:~/oscimpDigital/linux_driver$ make install_nfsdir
make -C add_const_core install; make -C axi_to_dac_core install; make -C data_dma_direct_core install; make -C data_to_ram_core install; make -C edfb_core install; make -C fft_core install; make -C fir_core install; make -C fpgagen_core install; make -C nco_counter_core install; make -C pidv3_axi_core install; make -C redpitaya_converters_12_core install; make -C switch_core install;
make[1]: Entering directory '/home/bernardo/oscimpDigital/linux_driver/add_const_core'
make -C ~/buildroot-2020.11.1//output/build/linux-xilinx-v2019.1 SUBDIRS=/home/bernardo/oscimpDigital/linux_driver/add_const_core modules ARCH=arm \
CROSS_COMPILE=~/buildroot-2020.11.1//output/host/bin/arm-linux-
make[2]: Entering directory '/home/bernardo/buildroot-2020.11.1/output/build/linux-xilinx-v2019.1'
  Building modules, stage 2.
  MODPOST 1 modules
make[2]: Leaving directory '/home/bernardo/buildroot-2020.11.1/output/build/linux-xilinx-v2019.1'
add_const_core.o
mkdir -p /nfs/redpitaya/modules
mkdir: cannot create directory ‘/nfs’: Permission denied
/home/bernardo/oscimpDigital/linux_driver/Makefile.inc:33: recipe for target 'install' failed`

My environment at the time of running:

`XDG_VTNR=7
LC_PAPER=de_BE.UTF-8
LC_ADDRESS=de_BE.UTF-8
XDG_SESSION_ID=c2
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/bernardo
LC_MONETARY=de_BE.UTF-8
CLUTTER_IM_MODULE=xim
SESSION=ubuntu
GPG_AGENT_INFO=/home/bernardo/.gnupg/S.gpg-agent:0:1
TERM=xterm-256color
VTE_VERSION=4205
SHELL=/bin/bash
OSCIMP_DIGITAL_APP=/home/bernardo/oscimpDigital/app
QT_LINUX_ACCESSIBILITY_ALWAYS_ON=1
WINDOWID=60880727
LC_NUMERIC=de_BE.UTF-8
OLDPWD=/home/bernardo/oscimpDigital
UPSTART_SESSION=unix:abstract=/com/ubuntu/upstart-session/1000/1238
GNOME_KEYRING_CONTROL=
GTK_MODULES=gail:atk-bridge:unity-gtk-module
OSCIMP_DIGITAL_IP=/home/bernardo/oscimpDigital/fpga_ip
USER=bernardo
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LC_TELEPHONE=de_BE.UTF-8
QT_ACCESSIBILITY=1
UNITY_HAS_3D_SUPPORT=true
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
BR_DIR=~/buildroot-2020.11.1/
DEFAULTS_PATH=/usr/share/gconf/ubuntu.default.path
XDG_CONFIG_DIRS=/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg
UNITY_DEFAULT_PROFILE=unity
DESKTOP_SESSION=ubuntu
PATH=/~/buildroot-2020.11.1/output/host/usr/bin:/home/bernardo/bin:/home/bernardo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/bernardo/oscimpDigital/app/tools/module_generator:/home/bernardo/oscimpDigital/fpga_ip/tools/:/home/bernardo/oscimpDigital/app/tools/module_generator:/home/bernardo/oscimpDigital/fpga_ip/tools/:/home/bernardo/oscimpDigital/app/tools/module_generator:/home/bernardo/oscimpDigital/fpga_ip/tools/
QT_IM_MODULE=ibus
QT_QPA_PLATFORMTHEME=appmenu-qt5
OSCIMP_DIGITAL_LIB=/home/bernardo/oscimpDigital/lib
LC_IDENTIFICATION=de_BE.UTF-8
XDG_SESSION_TYPE=x11
PWD=/home/bernardo/oscimpDigital/linux_driver
JOB=unity-settings-daemon
XMODIFIERS=@im=ibus
GNOME_KEYRING_PID=
LANG=en_US.UTF-8
GDM_LANG=en_US
MANDATORY_PATH=/usr/share/gconf/ubuntu.mandatory.path
LC_MEASUREMENT=de_BE.UTF-8
COMPIZ_CONFIG_PROFILE=ubuntu
IM_CONFIG_PHASE=1
OSCIMP_DIGITAL_DRIVER=/home/bernardo/oscimpDigital/linux_driver
OSCIMP_DIGITAL_NFS=/nfs
GDMSESSION=ubuntu
SESSIONTYPE=gnome-session
GTK2_MODULES=overlay-scrollbar
SHLVL=1
HOME=/home/bernardo
XDG_SEAT=seat0
LANGUAGE=en_US
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
UPSTART_INSTANCE=
UPSTART_EVENTS=xsession started
XDG_SESSION_DESKTOP=ubuntu
LOGNAME=bernardo
COMPIZ_BIN_PATH=/usr/bin/
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-HMmCGZ5wBW
XDG_DATA_DIRS=/usr/share/ubuntu:/usr/share/gnome:/usr/local/share:/usr/share:/var/lib/snapd/desktop
QT4_IM_MODULE=xim
LESSOPEN=| /usr/bin/lesspipe %s
INSTANCE=
UPSTART_JOB=unity7
BOARD_NAME=redpitaya
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
IP=10.42.0.1
XDG_CURRENT_DESKTOP=Unity
GTK_IM_MODULE=ibus
LESSCLOSE=/usr/bin/lesspipe %s %s
LC_TIME=de_BE.UTF-8
LC_NAME=de_BE.UTF-8
XAUTHORITY=/home/bernardo/.Xauthority
_=/usr/bin/env`

I should add some considerations:
The buildroot-2020.11.1 is untouched besides the instructions given in the Wiki.
The file Makefile.inc is indeed in the parent directory.

Anything else that would help this debugging I can happily provide.

Thank you very much for the help!

**Comment by trabucayre** [comment]
Hello,
in fact there is two problems:
- with `sudo` your environment variables are not exported this why you have `Makefile:2: /Makefile.inc: No such file or directory`
- your second try with user right can't write into /nfs because this directory was created by root

In fact explanation is [here](https://github.com/oscimp/oscimpDigital/wiki/2Prepare#finalize-the-configuration-of-the-host-computer):
- sudo mkdir /nfs
- sudo chown -R $(id -u).$(id -g) /nfs
But I'm agree these details are too late in the process and has to be moved before installing drivers

**Comment by jmfriedt** [comment]
You have set your host IP address to
```
 address 10.42.0.1
```
and you are trying to ssh to this address, so the root prompt is that of your host computer, not the redpitaya. You should ssh to the Redpitaya IP address and make sure you select an IP address for the host on the same subnet than the target.
