### ISSUE TITLE
NFS mount - connection timed out

### ISSUE THREAD

**Issue by BernardoMadeira** [oscimp/oscimpDigital#2]
Hello once again.

**I am encountering a problem regarding mounting the nfs folder on the red pitaya.**

I have tried debugging it, but with no success.

**1. I am able to ping the RP from my host computer.**

bernardo@bernardo-ThinkPad-X230:~/oscimpDigital$ ping 192.168.0.10
PING 192.168.0.10 (192.168.0.10) 56(84) bytes of data.
64 bytes from 192.168.0.10: icmp_seq=1 ttl=64 time=0.225 ms

**and vice-versa:**

redpitaya> ping 192.168.0.1
PING 192.168.0.1 (192.168.0.1): 56 data bytes
64 bytes from 192.168.0.1: seq=0 ttl=64 time=0.402 ms

All necessary files are sourced:
source redpitaya/sourceme.ggm
source oscimpDigital/settings.sh
source /tools/Xilinx/Vivado/2019.2/settings64.sh
export PATH=/buildroot-2020.11.1/output/host/usr/bin:$PATH

are executed everytime I open a new terminal

My exports  file in RP:

/nfs *(rw,no_root_squash,sync,no_subtree_check)

My fstab file (I have tried both the existing line and the one present in the wiki, chapter 2. Prepare):

GNU nano 5.2                  New Buffer                  Modified  
# <file system> <mount pt>      <type>  <options>       <dump>  <pass>
/dev/root       /               ext2    rw,noauto       0       1
proc            /proc           proc    defaults        0       0
devpts          /dev/pts        devpts  defaults,gid=5,mode=620 0    >
tmpfs           /dev/shm        tmpfs   mode=0777       0       0
tmpfs           /tmp            tmpfs   mode=1777       0       0
tmpfs           /run            tmpfs   mode=0755,nosuid,nodev  0    >
sysfs           /sys            sysfs   defaults        0       0
/dev/mmcblk0p1  /boot   vfat    defaults        0       0
configfs    /sys/kernel/config configfs defaults 0  0
192.168.0.1:/nfs/redpitaya /usr/local nfs defaults,noauto,nolock 0  0
#192.168.0.2:/nfs/redpitaya16 /usr/local nfs defaults,noauto,nolock 0>
#192.168.0.1:/nfs /usr/local nfs defaults,noauto,nolock 0  0

I have nfs-kernel-server and nfs-common installed and updated. I have uninstalled and re-installed to see if that would fix the situation but it did not. I have checked the ports used by nfs (followed https://serverfault.com/questions/377170/which-ports-do-i-need-to-open-in-the-firewall-to-use-nfs) and I disabled the firewall for those ports. 

When executing the last command on Chapter 2, I get a connection timed out error in the red pitaya.

redpitaya> mount /usr/local
mount: mounting 192.168.0.1:/nfs/redpitaya on /usr/local failed: Connection timed out

Is there a log that could hint me what could be originating this error?

Could the cause be the location of the nfs folder and the path interpretation depending if you are root or not when doing the last steps of Chapter 2 on the host computer? 

I have tried doing the final steps both at the oscimpDigital folder and using sudo su and following the steps from there.
In the last case, the nfs folder will be created in the SSD where the host computer system folders are. Here if I am not mistaken is where I think ~ is interpreted differently.
The combination of the **settings.sh** file, the **export file** and the **fstab** file not matching is something that I would like to take out of the way before assuming it is a networking problem. What is the default location of the NFS folder in a working environment?

**Comment by mer0m** [comment]
Hi,

I tried to reproduce your issue with the wiki commands.
In order to have a minimal env, I did not source the settings*.sh or other vivado settings files.
On my side, I had a permission error when I mount from the redpitaya because the `/nfs` is owned by root:root.
If your current user is not allowed to write in /nfs, the oscimp drivers install and the bitstream/app dispatching will require `sudo` or root rights.

Here the commands I use to make a working nfs server on the PC:
`sudo mkdir /nfs`
`sudo chown -R $(id -u).$(id -g) /nfs`
`touch /nfs/aFileOnNfs`
Add `/nfs *(rw,no_root_squash,sync,no_subtree_check)` at the end of my `/etc/exports`
`sudo service nfs-kernel-server restart`

On the redpitaya, assuming 192.168.0.1 is the PC ip address:
Add `192.168.0.1:/nfs /usr/local nfs defaults,noauto,nolock 0  0` at the end of `/etc/fstab`
`mount /usr/local`
`ls /usr/local`

**Comment by BernardoMadeira** [comment]
I re-started my buildroot from scratch and the same error appeared.
I could ping both the RP and the host computer from each other. The nfs folder had all the right permissions.
Turned out it was a firewall problem? After that I could mount it easily.
Thank you very much for the help.

A note: when re-doing the buildroot, an error was given regarding this problem: https://stackoverflow.com/questions/70663523/the-unauthenticated-git-protocol-on-port-9418-is-no-longer-supported
Solution is also there, but it might be worth mentioning it for people who install it in the future.

Everything regarding the Chapter 4. Testing went smoothly until I got this error:

```
File "/usr/lib/python3.9/site-packages/remi/gui.py", line 32, in <module>
ModuleNotFoundError: No module named 'HTMLParser'

During handling of the above exception, another exception occurred

Traceback (most recent call last):
  File "/usr/local/redpitaya/double_dds/bin/./double_dds_webserver.py", line 8, in <module>
    import remi.gui as gui
  File "/usr/lib/python3.9/site-packages/remi/__init__.py", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/remi/gui.py", line 40, in <module>
AttributeError: 'HTMLParser' object has no attribute 'unescape'
```

I have tried re-installing the libraries, drivers and the module-generator - as well as double-check if my buildroot includes all the necessary packages (it does), but it does not fix the problem.
Thank you very much for the efforts in getting this to work for me.

**Comment by mer0m** [comment]
Did you ```make clean``` your buildroot before making a new one ?
I recommend you to :
- ```cd $HOME/${BR_DIR:2}```, ```make clean```, ```make redpitaya_defconfig```, 
- modify the ```git://``` to ```https://``` where it's necessary in your ```.config``` (according to the new github policy)
- ```make```
- ```make menuconfig``` to add python3, remi, zmq and lxml support
- ```cd $OSCIMP_DIGITAL_LIB```, ```make``` and ```make install``` the lib
- check your ```${BR2_EXTERNAL%:}/board/redpitaya/overlay/```, especially the interfaces and the fstab
- ```cd $HOME/${BR_DIR:2}``` and finally ```make``` to add the new packages

Because the buildroot version is the same that your previous one, you don't have to rebuild your drivers.
You can also keep your double_dds project.

When your buildroot is on the redpitaya, ssh to it and check the output of the following commands:
```bash
redpitaya> cat /etc/os-release 
NAME=Buildroot
VERSION=2020.11.1
ID=buildroot
VERSION_ID=2020.11.1
PRETTY_NAME="Buildroot 2020.11.1"
redpitaya> python
Python 3.9.0 (default, Jan 30 2021, 18:46:09) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import remi
>>> remi
<module 'remi' from '/usr/lib/python3.9/site-packages/remi/__init__.py'>
```

**Comment by trabucayre** [comment]
Before cleaning anything: your `/etc/exports` is in your RP or in your computer? If it's in your RP it's wrong you have to fill this file on the host side

**Comment by BernardoMadeira** [comment]
> "Before cleaning anything: your /etc/exports is in your RP or in your computer? If it's in your RP it's wrong you have to fill this file on the host side"

My /etc/exports in my host computer looks like this:

`/nfs *(rw,no_root_squash,sync,no_subtree_check)
`
After running the code it outputs this:

`redpitaya> cat /etc/os-release
NAME=Buildroot
VERSION=2020.11.1
ID=buildroot
VERSION_ID=2020.11.1
PRETTY_NAME="Buildroot 2020.11.1"
redpitaya> python
Python 3.9.0 (default, Apr 13 2022, 11:28:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import remi 
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/remi/gui.py", line 32, in <module>
ModuleNotFoundError: No module named 'HTMLParser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/remi/__init__.py", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/remi/gui.py", line 40, in <module>
AttributeError: 'HTMLParser' object has no attribute 'unescape'
>>> remi
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'remi' is not defined`

I am trying to search the internet regarding the error **AttributeError: 'HTMLParser' object has no attribute 'unescape'** but I don't want to break anything in the process. I see some people saying that HTMLParser.unescape was deprecated in Python3.9.

**Comment by BernardoMadeira** [comment]
So, first of all I went back to make menuconfig and instead of using openssl I switched to libressl in Libraries/Crypto/Openssl support/ssl library  >>> switch to libressl

After that I did a full rebuild with:
`make clean all`

I followed all the steps that @mer0m and @trabucayre described, double-checked everything. Re-made libraries, copied fpga_oscimp files with **make install_ssh**.

And lastly I went to the buildroot folder, grabbed gui.py from the remi folder and switched the order of the code. Put it on the nfs folder and copied from there using **cp gui.py /usr/lib/python3.9/site-packages/remi**
Because python will check first for a .py file to run, it will run gui.py instead of gui.pyc, bypassing the error.

`try:
    # Python 3.4+
        import html
	unescape = html.unescape

except ImportError:
    # Python 3
    try:
        from html.parser import HTMLParser
        h = HTMLParser()
        unescape = h.unescape
    except ImportError:
    	# Python 2.6-2.7
    	from HTMLParser import HTMLParser
    	h = HTMLParser()
    	unescape = h.unescape`

The reason of the error?
The code tries to run code made with Python2.X in mind and subsequently for newer versions. Because I knew that my version is 3.9, I just took the code that uses the html library instead of HTMLParser (deprecated) and put it first, and the later code as an exception.
I think the exception handler wasn't... Handling the exception due to it being defined as something different (I don't think it is an ImportError). This solution works but obviously it is not pretty.

In sum:
I runned the double_dds example. Blue led is flashing. No error messages. I can open the web server too.
I'd like to thank you all for really taking the time to help me here. Looking forward to using your platform.

Regards,
Bernardo
